spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      zone: ${local.ip}
      cache:
        enabled: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/jetlinks
    username: postgres
    password: jetlinks
    pool:
      max-size: 32
easyorm:
  default-schema: public # 数据库默认的schema
  dialect: postgres #数据库方言
logging:
  level:
    org.jetlinks: debug
    rule.engine: debug
    org.hswebframework: debug
    org.springframework.transaction: debug
    org.springframework.data.r2dbc.connectionfactory: debug
    io.micrometer: warn
    org.hswebframework.expands: error
    system: warn
    org.jetlinks.rule.engine: debug
    org.jetlinks.gateway: debug
    org.springframework: warn
    org.apache.kafka: warn
    org.jetlinks.pro.device.message.writer: debug